image_width: 640
image_height: 480
camera_name: cam_0
camera_matrix:
  rows: 3
  cols: 3
  data: [1088.60442,    0.     ,  314.54243,
            0.     , 1090.75158,  220.77703,
            0.     ,    0.     ,    1.     ]
distortion_model: plum_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.091006, 2.735876, -0.001135, -0.004749, -20.789586]
projection_matrix:
  rows: 3
  cols: 4
  data: [1., 0., 0., 0.,
         0., 1., 0., 0.,
         0., 0., 1., 0.]
single camera reprojection error (mean squared):
  data: 0.29903504166474704
stereo reprojection error (mean squared):
  data: 0.3822677852778425
