camera0: 2
camera1: 4
frame_width: 640
frame_height: 480
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 1
checkerboard_box_size_scale : 0.5
checkerboard_rows: 5
checkerboard_columns: 7
cooldown: 75
